// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsffgtymddavtbegyigm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzZmZndHltZGRhdnRiZWd5aWdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjI5MjcsImV4cCI6MjA2NTM5ODkyN30.XRi8ujoQUSkQA6dJxUo_z5QLB-y9PkcImmkrNNm99Ew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);